# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=10)),
                ('state', models.BooleanField()),
                ('current', models.FloatField()),
                ('voltage', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='client',
        ),
    ]
