# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_1', '0003_msg_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userId',
            field=models.CharField(default='de000', max_length=10),
        ),
    ]
