# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_1', '0007_remove_msg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='topic',
            field=models.CharField(max_length=50),
        ),
    ]
