# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_1', '0008_auto_20171113_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userId',
            field=models.CharField(default='de000', max_length=50),
        ),
    ]
