# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_1', '0009_auto_20171125_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='act',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='cmd',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='power',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='users',
            name='unit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='users',
            name='userId',
            field=models.CharField(default='000000000000', max_length=50),
        ),
    ]
